# Generated by Django 3.2.4 on 2021-06-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='next_date',
        ),
    ]
