# Generated by Django 3.2.4 on 2021-06-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_remove_taxes_next_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userid',
            new_name='userId',
        ),
    ]
